import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { NavbarDemo } from "@/components/Navbar";
import { Spotlight } from "@/components/ui/Spotlight";
import { ModeToggle } from "@/components/ui/toggle-mode";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Priyanshu Singh",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>


					<NavbarDemo  />
					<div className="fixed md:top-4 md:right-4 z-10 bottom-4 right-4">
						<ModeToggle />
					</div>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
