import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { NavbarDemo } from "@/components/Navbar";
import { Spotlight } from "@/components/ui/Spotlight";
import { ModeToggle } from "@/components/ui/toggle-mode";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Priyanshu Singh",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
					<NavbarDemo />
					<div className="fixed md:top-4 md:right-4 z-10 bottom-4 right-4">
						<ModeToggle />
					</div>
					<div className=" absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black dark: bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]" />
					<div className="h-full w-full dark:bg-black bg-white  dark:bg-dot-white/[0.2] bg-dot-black/[0.2] relative flex items-center justify-center">
						<div className=" h-full w-screen">
							<Spotlight className="-top-40 left-0 md:left-60 md:-top-20" fill="white" />
							{children}
						</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
